engines:
  eslint:
    enabled: true
    checks:
      complexity:
        enabled: true
  requiresafe:
    enabled: true

ratings:
  paths:
    - "**.js"
    - "**.es6"

exclude_paths:
  - "test/**/*"
